lightbox: true
project:
  type: book
  output-dir: docs 
book:
  title: "Astroparticle Physics"
  author: "J. A. Aguilar"
  site-url: https://zemrude.github.io/AstroParticles/
  search: true
  downloads: [pdf]
  date: "4/10/2024"
  
  chapters:
    - index.qmd
    - part: "Physics Introduction"
      chapters:
      - chap1.qmd
    - part: "Cosmic Rays"
      chapters:
      - chap2.qmd
      - chap3.qmd
    - part: "Multimessenger Astronomy"
      chapters:
      - chap4.qmd
    - part: "Dark Matter"
      chapters:
      - chap5.qmd
    - part: "References"
      chapters:
      - references.qmd
number-depth: 1

bibliography: references.bib
  

jupyter: python3

format:
  html:
    theme: 
    - cosmo 
  pdf: default
   

