lightbox: true
project:
  type: book
  output-dir: docs 
book:
  title: "Astroparticle Physics"
  author: "J. A. Aguilar"
  site-url: https://zemrude.github.io/AstroParticles/
  search: true
  downloads: [pdf]
  date: "4/10/2024"
  
  chapters:
    - index.qmd
    - part: "Physics Introduction"
      chapters:
      - chap1_0.qmd
      - chap1_1.qmd
      - chap1_2.qmd
      - chap1_3.qmd
    - part: "Cosmic Rays"
      chapters:
      - chap2_0.qmd
      - chap2_1.qmd
    - part: "Cosmic Rays in the Atmosphere"
      chapters:
      - chap3_0.qmd
      - chap3_1.qmd
      - chap3_2.qmd
    - part: "Multimessenger Astronomy"
      chapters:
      - chap4_0.qmd
      - chap4_1.qmd
      - chap4_2.qmd
      - chap4_3.qmd
    - part: "Dark Matter"
      chapters:
      - chap5.qmd
    - part: "References"
      chapters:
      - references.qmd
number-depth: 1

bibliography: references.bib
  
from: markdown+emoji
jupyter: python3

format:
  html:
    theme: 
    - cosmo 
  pdf: default
   

